"""Synthetic travel-interaction generator.

============================================================================
THESE ARE NOT REAL TRAVELLERS. Every user, trip and timestamp in the output of
this module is generated by the model below. No real person's travel history is
represented, and no conclusion about actual human travel behaviour may be drawn
from results measured on this data.
============================================================================

WHY SYNTHETIC
-------------
No public dataset of per-user travel histories exists under a licence that
permits redistribution, at the geographic scope this project needs. The
destination data is entirely real (GeoNames, OpenStreetMap, Open-Meteo, World
Bank, Wikipedia); only the *interactions* are simulated, and the two are kept
in separate files so the boundary is never ambiguous.

WHAT THE EVALUATION NUMBERS MEAN
--------------------------------
Metrics computed on this data measure how well each model recovers the
structure the generator injected -- preference archetypes, geographic chaining
and popularity bias. That is a genuine, non-trivial learning problem and it
validates that the pipeline works end to end. It is *not* evidence of
real-world recommendation accuracy, and the README says so.

GENERATIVE MODEL
----------------
Each user draws:

* a preference archetype (a weight vector over measured OSM profile
  categories, optionally blended with a second archetype);
* a home region, sampled proportionally to real destination popularity;
* a budget preference and a travel-season preference.

Each trip is then drawn from one of three mechanisms, so that no single
recommender family can trivially explain all of the data:

1. *preference*  - softmax over archetype affinity, cost fit and season fit;
2. *popularity*  - sampled from the real popularity proxy distribution;
3. *geographic*  - sampled near the previous destination (trip chaining).
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Dict, List, Optional, Sequence, Tuple

import numpy as np
import pandas as pd

from src.preprocessing.features import PROFILE_CATEGORIES
from src.utils.geo import distance_decay, pairwise_distance_matrix
from src.utils.logging_utils import get_logger

LOGGER = get_logger(__name__)

# Preference archetypes over the measured OSM profile categories. The weights
# express *what a traveller type cares about*; the values a destination has for
# those categories are measured, not invented.
ARCHETYPES: Dict[str, Dict[str, float]] = {
    "culture_seeker": {"museums": 1.0, "culture": 0.9, "heritage": 0.8, "architecture": 0.7},
    "nightlife_lover": {"nightlife": 1.0, "food": 0.6, "shopping": 0.4, "culture": 0.3},
    "foodie": {"food": 1.0, "shopping": 0.5, "nightlife": 0.4, "culture": 0.3},
    "nature_escaper": {"nature": 1.0, "outdoor": 0.9, "beaches": 0.4},
    "beach_holidaymaker": {"beaches": 1.0, "food": 0.5, "nightlife": 0.4, "outdoor": 0.3},
    "family_traveller": {"family": 1.0, "nature": 0.6, "museums": 0.4, "walkability": 0.4},
    "city_walker": {"walkability": 1.0, "architecture": 0.8, "culture": 0.6, "food": 0.5},
    "history_buff": {"heritage": 1.0, "architecture": 0.8, "museums": 0.7},
}

ARCHETYPE_NAMES: Tuple[str, ...] = tuple(ARCHETYPES)

BUDGET_LEVELS: Tuple[str, ...] = ("budget", "mid-range", "expensive")


@dataclass(frozen=True)
class GeneratorSettings:
    """Tunable knobs for the synthetic generator (mirrors ``configs``)."""

    n_users: int = 4000
    min_trips: int = 3
    max_trips: int = 12
    preference_sharpness: float = 6.0
    popularity_mix: float = 0.30
    geo_chain_prob: float = 0.35
    geo_chain_scale_km: float = 700.0
    seed: int = 42


def _archetype_matrix(categories: Sequence[str]) -> np.ndarray:
    """Return the (n_archetypes x n_categories) L2-normalised weight matrix."""
    matrix = np.zeros((len(ARCHETYPES), len(categories)), dtype="float64")
    for row, weights in enumerate(ARCHETYPES.values()):
        for column, category in enumerate(categories):
            matrix[row, column] = weights.get(category, 0.0)
    norms = np.linalg.norm(matrix, axis=1, keepdims=True)
    norms[norms == 0] = 1.0
    return matrix / norms


def _softmax(scores: np.ndarray) -> np.ndarray:
    """Numerically stable softmax over the final axis."""
    shifted = scores - np.max(scores)
    exponentiated = np.exp(shifted)
    total = exponentiated.sum()
    if not np.isfinite(total) or total <= 0:
        return np.full_like(scores, 1.0 / len(scores))
    return exponentiated / total


def generate_interactions(
    destinations: pd.DataFrame,
    settings: GeneratorSettings,
) -> Tuple[pd.DataFrame, pd.DataFrame]:
    """Generate synthetic users and their ordered trip histories.

    Returns
    -------
    interactions:
        One row per trip: ``user_id, destination_id, trip_index, month,
        trip_duration_days, budget, rating, mechanism``. ``mechanism`` records
        which generative branch produced the trip and exists purely for
        diagnostics -- no model is allowed to consume it.
    users:
        One row per user with the latent attributes used to generate them.
    """
    rng = np.random.default_rng(settings.seed)
    n_destinations = len(destinations)
    if n_destinations < 20:
        raise ValueError("Need at least 20 destinations to generate interactions")

    categories = list(PROFILE_CATEGORIES)
    profile_columns = [f"profile_{name}" for name in categories]
    profiles = destinations[profile_columns].astype("float64")
    profiles = profiles.fillna(profiles.mean(axis=0)).to_numpy()
    # Standardise so that a category with a naturally large share (restaurants)
    # does not dominate every archetype's affinity.
    profiles = (profiles - profiles.mean(axis=0)) / (profiles.std(axis=0) + 1e-9)

    archetypes = _archetype_matrix(categories)
    affinity = profiles @ archetypes.T  # (n_destinations, n_archetypes)
    affinity = (affinity - affinity.mean(axis=0)) / (affinity.std(axis=0) + 1e-9)

    popularity = destinations["popularity_score"].to_numpy(dtype="float64")
    popularity_probabilities = popularity**2  # squared -> a realistic heavy head
    popularity_probabilities = popularity_probabilities / popularity_probabilities.sum()

    cost_percentile = destinations["cost_percentile"].to_numpy(dtype="float64")
    season_columns = [f"season_score_m{month:02d}" for month in range(1, 13)]
    season_scores = destinations[season_columns].to_numpy(dtype="float64")

    distances = pairwise_distance_matrix(
        destinations["latitude"].to_numpy(), destinations["longitude"].to_numpy()
    )

    # Users are seeded near popular destinations, mimicking that travellers
    # come disproportionately from well-connected places.
    home_indices = rng.choice(n_destinations, size=settings.n_users, p=popularity_probabilities)

    user_records: List[Dict[str, object]] = []
    interaction_records: List[Dict[str, object]] = []

    for user_number in range(settings.n_users):
        user_id = f"u{user_number:06d}"
        primary = int(rng.integers(len(ARCHETYPE_NAMES)))
        secondary = int(rng.integers(len(ARCHETYPE_NAMES)))
        blend = float(rng.uniform(0.6, 1.0))
        # A blended taste vector keeps users from collapsing into 8 clusters.
        user_affinity = blend * affinity[:, primary] + (1.0 - blend) * affinity[:, secondary]

        budget_level = int(rng.integers(len(BUDGET_LEVELS)))
        budget_target = (budget_level + 0.5) / len(BUDGET_LEVELS)
        budget_strictness = float(rng.uniform(0.5, 2.5))

        preferred_month = int(rng.integers(1, 13))
        home = int(home_indices[user_number])
        home_pull = float(rng.uniform(0.0, 1.2))

        n_trips = int(rng.integers(settings.min_trips, settings.max_trips + 1))
        visited: List[int] = []
        previous: Optional[int] = None

        for trip_index in range(n_trips):
            # Trip context is drawn first; it conditions destination choice.
            month = int(np.clip(round(rng.normal(preferred_month, 1.6)), 1, 12))
            if month < 1:
                month += 12
            duration = int(np.clip(rng.gamma(shape=3.0, scale=1.8) + 2, 2, 21))
            budget = BUDGET_LEVELS[budget_level]

            mechanism_draw = rng.random()
            chain_available = previous is not None
            if mechanism_draw < settings.popularity_mix:
                mechanism = "popularity"
                probabilities = popularity_probabilities.copy()
            elif chain_available and mechanism_draw < settings.popularity_mix + settings.geo_chain_prob:
                mechanism = "geographic"
                proximity = distance_decay(distances[previous], settings.geo_chain_scale_km)
                # Chaining still respects taste, just weakly.
                probabilities = proximity * np.exp(0.5 * user_affinity)
                probabilities = probabilities / probabilities.sum()
            else:
                mechanism = "preference"
                cost_fit = -budget_strictness * np.abs(cost_percentile - budget_target)
                season_fit = 1.5 * season_scores[:, month - 1]
                home_fit = home_pull * distance_decay(distances[home], 1500.0)
                utility = (
                    settings.preference_sharpness * user_affinity
                    + 2.0 * cost_fit
                    + season_fit
                    + home_fit
                    # A mild popularity term: even taste-driven travellers are
                    # more likely to have heard of well-known places.
                    + 1.0 * popularity
                )
                probabilities = _softmax(utility)

            # Never revisit inside one history: the task is "where NEXT".
            if visited:
                probabilities = probabilities.copy()
                probabilities[visited] = 0.0
                total = probabilities.sum()
                if total <= 0:
                    break
                probabilities /= total

            choice = int(rng.choice(n_destinations, p=probabilities))
            visited.append(choice)

            interaction_records.append(
                {
                    "user_id": user_id,
                    "destination_id": destinations.iat[choice, destinations.columns.get_loc("destination_id")],
                    "trip_index": trip_index,
                    "month": month,
                    "trip_duration_days": duration,
                    "budget": budget,
                    # A 1-5 rating derived from the same latent utility, so the
                    # data supports rating-aware models later if wanted.
                    "rating": float(np.clip(rng.normal(3.9 + 0.4 * user_affinity[choice], 0.7), 1.0, 5.0)),
                    "mechanism": mechanism,
                }
            )
            previous = choice

        user_records.append(
            {
                "user_id": user_id,
                "archetype_primary": ARCHETYPE_NAMES[primary],
                "archetype_secondary": ARCHETYPE_NAMES[secondary],
                "archetype_blend": blend,
                "budget": BUDGET_LEVELS[budget_level],
                "preferred_month": preferred_month,
                "home_destination_id": destinations.iat[home, destinations.columns.get_loc("destination_id")],
                "n_trips": len(visited),
            }
        )

    interactions = pd.DataFrame(interaction_records)
    users = pd.DataFrame(user_records)
    LOGGER.info(
        "Generated %d synthetic interactions for %d users over %d destinations",
        len(interactions),
        len(users),
        n_destinations,
    )
    LOGGER.info("Mechanism mix: %s", interactions["mechanism"].value_counts(normalize=True).round(3).to_dict())
    return interactions, users


def settings_from_config(config) -> GeneratorSettings:
    """Build :class:`GeneratorSettings` from a loaded :class:`~src.config.Config`."""
    return GeneratorSettings(
        n_users=int(config.get("interactions.n_users", 4000)),
        min_trips=int(config.get("interactions.min_trips", 3)),
        max_trips=int(config.get("interactions.max_trips", 12)),
        preference_sharpness=float(config.get("interactions.preference_sharpness", 6.0)),
        popularity_mix=float(config.get("interactions.popularity_mix", 0.30)),
        geo_chain_prob=float(config.get("interactions.geo_chain_prob", 0.35)),
        geo_chain_scale_km=float(config.get("interactions.geo_chain_scale_km", 700.0)),
        seed=config.seed,
    )
